version: '3.1'

services:
    db:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_list_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: password
        volumes:
            - ./vendor/db_scripts/:/docker-entrypoint-initdb.d/
        ports:
            - "4406:3306"